' Deployment Diagram
' Description - It depicts the physical resources in a system, including nodes, components, and connections

' Relation in between symbols
' --------------
' |   Symbol   |
' |------------|
' |     --     |
' |     ..     |
' |     ~~     |
' |     ==     |
' --------------

@startuml
' Style area

' Icons area

' Skip Parameteres

' Header Title area

' all deployment key definition
actor actor
agent agent
artifact artifact
boundary boundary
card card
cloud cloud
component component
control control
database database
entity entity
file file
folder folder
frame frame
interface  interface
node node
package package
queue queue
stack stack
rectangle rectangle
storage storage
usecase usecase

actor1 -- actor2 : label1
actor1 .. actor3 : label2
actor1 ~~ actor4 : label3
actor1 == actor5

@enduml